package Entidades;
// Generated 14/03/2023, 4:56:39 p.�m. by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import java.util.Set;

/**
 * Permisos generated by hbm2java
 */
@Entity
@Table(name="permisos")
public class Permisos implements java.io.Serializable {
@Id
@Column(name="idPermisos")
	private int idPermisos;
@Column(name="nombre")
	private String nombre;
@Column(name="descripcion")
	private String descripcion;
@Column
@ElementCollection(targetClass=Integer.class)
	private Set roleses = new HashSet(0);

	public Permisos() {
	}

	public Permisos(int idPermisos, String nombre, String descripcion) {
		this.idPermisos = idPermisos;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Permisos(int idPermisos, String nombre, String descripcion, Set roleses) {
		this.idPermisos = idPermisos;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.roleses = roleses;
	}

	public int getIdPermisos() {
		return this.idPermisos;
	}

	public void setIdPermisos(int idPermisos) {
		this.idPermisos = idPermisos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set roleses) {
		this.roleses = roleses;
	}

}
