package Entidades;
// Generated 14/03/2023, 4:56:39 p.�m. by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles")
public class Roles implements java.io.Serializable {
	@Id
	@Column(name="idRoles")
	private int idRoles;
	@Column(name="nombre")
	private String nombre;
	@Column(name="descripcion")
	private String descripcion;
	@Column(name="attribute6")
	private String attribute6;
	@Column
	@ElementCollection(targetClass=Integer.class)
	private Set permisoses = new HashSet(0);
	@Column
	@ElementCollection(targetClass=Integer.class)
	private Set usuarioses = new HashSet(0);

	public Roles() {
	}

	public Roles(int idRoles, String nombre, String descripcion) {
		this.idRoles = idRoles;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Roles(int idRoles, String nombre, String descripcion, String attribute6, Set permisoses, Set usuarioses) {
		this.idRoles = idRoles;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.attribute6 = attribute6;
	this.permisoses = permisoses;
		this.usuarioses = usuarioses;
	}

	public int getIdRoles() {
		return this.idRoles;
	}

	public void setIdRoles(int idRoles) {
		this.idRoles = idRoles;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getAttribute6() {
		return this.attribute6;
	}

	public void setAttribute6(String attribute6) {
		this.attribute6 = attribute6;
	}

	public Set getPermisoses() {
		return this.permisoses;
	}

	public void setPermisoses(Set permisoses) {
		this.permisoses = permisoses;
	}

	public Set getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set usuarioses) {
		this.usuarioses = usuarioses;
	}

}
