package Entidades;
// Generated 14/03/2023, 4:56:39 p.�m. by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios")
public class Usuarios implements java.io.Serializable {
	@Id
	@Column(name="idUsuario")
	private int idUsuario;
	@Column(name="nombre")
	private String nombre;
	@Column(name="contrasena")
	private String contrasena;
	@Column(name="roleses")
	private Set roleses = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(int idUsuario, String nombre, String contrasena) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
		this.contrasena = contrasena;
	}

	public Usuarios(int idUsuario, String nombre, String contrasena, Set roleses) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
		this.contrasena = contrasena;
		this.roleses = roleses;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public Set getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set roleses) {
		this.roleses = roleses;
	}

}
